import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import '@/core/ui/componentes/menu/styles/stilos.css'
import Home from "./page";
import { SidebarNotification } from "@/core/ui/componentes/menu/menu";

export const metadata: Metadata = {
  title: "SwiftPay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  title,
}: {
  children: React.ReactNode;
  title: string;
}) {
  return (
    <html className="h-screen w-screen">
      <body className="h-screen w-screen" style={{background: "#EFF1F3"}}>
        <main className='w-full h-full bg-[#EFF1F3]'>
        <div className="container">
          <SidebarNotification />
          <div className="content">
           {children}
         </div>

        </div>
        </main>
      </body>
    </html>
  );
}
