import type { Metadata } from "next";

import '@/core/infra/ports/react/componentes/menu/styles/stilos.css'
import { SidebarNotification } from "@/core/infra/ports/react/componentes/menu/menu";

export const metadata: Metadata = {
  title: "SwiftPay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  title: string;
}) {
  return (
    <html className="h-screen w-screen">
      <body className="h-screen w-screen" style={{background: "#EFF1F3"}}>
        <main className='w-full h-full bg-[#EFF1F3]'>
        <div className="container">
          <SidebarNotification />
          <div className="content">
           {children}
         </div>

        </div>
        </main>
      </body>
    </html>
  );
}
