export const specialties = [
    { value: "cardiologia", label: "Cardiologia" },
    { value: "dermatologia", label: "Dermatologia" },
    { value: "neurologia", label: "Neurologia" },
    { value: "pediatria", label: "Pediatria" },
    { value: "ortopedia", label: "Ortopedia" },
    { value: "oftalmologia", label: "Oftalmologia" },
    { value: "ginecologia", label: "Ginecologia" },
    { value: "psiquiatria", label: "Psiquiatria" },
    { value: "endocrinologia", label: "Endocrinologia" },
    { value: "gastroenterologia", label: "Gastroenterologia" },
    { value: "urologia", label: "Urologia" },
    { value: "pneumologia", label: "Pneumologia" },
    { value: "otorrinolaringologia", label: "Otorrinolaringologia" },
    { value: "hematologia", label: "Hematologia" },
    { value: "geriatria", label: "Geriatria" },
    { value: "anestesiologia", label: "Anestesiologia" },
    { value: "alergologia", label: "Alergologia" },
    { value: "nefrologia", label: "Nefrologia" },
    { value: "reumatologia", label: "Reumatologia" },
  ];